import Header from "@/components/header/header"
import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"
import "./globals.css"

const inter = Open_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          "h-screen bg-cover bg-no-repeat max-w-[1440px] mx-auto"
        }>
        <Header />
        <div className="py-2">{children}</div>
        <footer className="text-center">@copy</footer>
      </body>
    </html>
  )
}
